---

## This file contains configuration for the access application, depending on the preferences of the user.

default: &default
  available_locales: # first locale is the default one
    - en
    - el
  default_phone_country: en
  email:
    default_from: no-reply@access.hellasgrid.gr

###### E-mail ######
development:
  <<: *default

production:
  <<: *default

test:
  <<: *default