---

- name: Checkout code from git
  git: repo={{ git_application_url }}
       dest={{ application_path }}
       update=yes
       version={{ application_branch }}
  notify: restart apache
  tags: install_access

# To be introduced in Ansible 2.0 (alpha version on September 2015)
# - name: Bundle install
#   bundler: state=present deployment=yes chdir={{ application_path }}/access/Gemfile

- name: Bundle install
  shell: bash -lc "bundle install" chdir="{{ application_path }}/access"
  become: yes
  become_user: "{{ application_user }}"
  notify: restart apache
  tags:
    - install_access
    - install_gems

- name: Copy secrets.yml
  template: src=config/secrets.yml.j2 dest={{application_path}}/access/config/secrets.yml
            owner={{ application_user }} group={{ application_user }} mode=0644
  notify: restart apache
  tags: install_access

##########################################################
########### Create necessary rails directories ###########
##########################################################
- name: Creates folder tmp
  file: path={{ application_path }}access/tmp state=directory
  tags:
    - create_rails_directories

- name: Creates folder cache
  file: path={{ application_path }}access/tmp/cache state=directory
  tags:
    - create_rails_directories

- name: Creates folder log
  file: path={{ application_path }}access/log state=directory
  tags:
    - create_rails_directories

- name: Creates file development.log
  file: path={{ application_path }}access/log/development.log state=touch
  tags:
    - create_rails_directories

#####################################
########### Rake db tasks ###########
#####################################
- name: rake db:migrate
  shell: bash -lc "rake db:migrate" chdir="{{ application_path }}/access"
  tags:
    - rake_db_tasks

# This task is to be run once. If the data have already been seeded and the seed
# file has changed, the process of updating has to be done manually.
# - name: rake db:seed
#   shell: bash -lc "rake db:seed" chdir="{{ application_path }}/access"
#   tags:
#     - rake_db_tasks

# tranfer all the data needed (e.g.database.yml)
# (maybe) run checks
